name: Publish to JSR

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.3

      - name: Check Deno version
        run: deno --version

      - name: Cache dependencies
        run: deno cache mod.ts

      - name: Format check
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --allow-env

      - name: Publish to JSR
        run: deno publish
