name: Publish to JSR

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.x"

      - name: Check Deno version
        run: deno --version

      - name: Clean and regenerate lockfile
        run: |
          rm -f deno.lock
          deno cache --reload mod.ts

      - name: Format check
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --allow-env

      - name: Publish to JSR
        run: deno publish
